NowaEdukacjaClient/Controllers/PowierzeniaController.cs
using NowaEdukacjaClient.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NowaEdukacjaClient.Controllers
{
    public class PowierzeniaController : BaseNowaEdukacjaController
    {
        PlanowaniePowierzenService.PlanowaniePowierzenService serwisPowierzenia = new PlanowaniePowierzenService.PlanowaniePowierzenService();
        ZIRPService.ZatwierdzanieIRaportowaniePowierzenService serwisZirp = new ZIRPService.ZatwierdzanieIRaportowaniePowierzenService();

        // GET: Przydzielaj
        public ActionResult Przydzielaj(PrzydzielajSearchModel Szukaj)
        {
            PrzydzielajSearchModel search;

            if (TempData["PowierzeniaPrzydzielajSzukaj"] != null)
            {
                search = (PrzydzielajSearchModel)TempData["PowierzeniaPrzydzielajSzukaj"];
            }
            else
            {
                search = Szukaj;
            }

            PrzydzielajViewModel viewModel = new PrzydzielajViewModel();

            viewModel.JednostkiOrganizacyjne = search.JednostkiOrganizacyjne;
            viewModel.Nazwisko = search.Nazwisko;
            viewModel.Imie = search.Imie;
            viewModel.Zainteresowanie = search.Zainteresowanie;
            viewModel.Tytul = search.Tytul;

            viewModel.CyklKsztalcenia = search.CyklKsztalcenia;
            viewModel.PlanStudiow = search.PlanStudiow;
            viewModel.Semestr = search.Semestr;

            try
            {
                //pobranie podstawowych danych z serwisów
                ZIRPService.JednostkaOrganizacyjna[] wszystkieJO = serwisZirp.getAllOrgUnits();//jest już posortowane
                ZIRPService.Stanowisko[] wszystkieStanowiska = serwisZirp.getAllJobTitles();

                ZIRPService.PracownikDydaktyczny[] pracownicyTabela = serwisZirp.getEmployeesByNameInterestTitle(
                    search.Imie,
                    search.Nazwisko,
                    search.Zainteresowanie,
                    search.Tytul);

                ZIRPService.CyklKsztalcenia[] wszystkieCK = serwisZirp.getAllEducationCycles();
                ZIRPService.PlanStudiow[] wszystkiePS = serwisZirp.getAllStudyPlans();
                ZIRPService.Semestr[] wszystkieSemestry = serwisZirp.getAllSemesters();

                ZIRPService.FormaZajec[] wszystkieFormyZajec = serwisZirp.getAllCourseForms();

                ZIRPService.Kurs[] kursy = serwisZirp.getCoursesByCyclePlanSemester(
                    search.CyklKsztalcenia, true,
                    search.PlanStudiow, true,
                    search.Semestr, true);

                int[] idKursow = kursy.Select(k => k.Id).ToArray();

                ZIRPService.Powierzenie[] powierzeniaTabela = serwisZirp.getCommittalsByCourses(idKursow);

                int[] idPowierzen = powierzeniaTabela.Select(p => p.Id).ToArray();

                ZIRPService.PracownikDydaktyczny[] pracownicyOdPowierzen = serwisZirp.getEmployeesByCommittals(idPowierzen);
                ZIRPService.Przedmiot[] przedmiotyOdKursow = serwisZirp.getSubjectsByCourses(idKursow);

                //generacja danych do ViewBagów
                var jednostkiOrg = new List<JednostkaOrganizacyjnaListModel>();
                foreach (var jo in wszystkieJO)
                {
                    jednostkiOrg.Add(new JednostkaOrganizacyjnaListModel
                    {
                        Id = jo.Id,
                        Nazwa = $"({jo.Skrot}) {jo.Nazwa}"
                    });
                }

                var cykleKsztalcenia = new List<GenericListModel>();
                foreach (var ck in wszystkieCK)
                {
                    cykleKsztalcenia.Add(new GenericListModel
                    {
                        Id = ck.Id,
                        Nazwa = $"{ck.Rok1}/{ck.Rok2}"
                    });
                }

                var planyStudiow = new List<GenericListModel>();
                foreach (var ps in wszystkiePS)
                {
                    planyStudiow.Add(new GenericListModel
                    {
                        Id = ps.Id,
                        Nazwa = $"{ps.Kierunek}, {Helpers.nazwaTryb(ps.Tryb)}, st.{ps.Stopien}, język {Helpers.nazwaJezyk(ps.Jezyk)}"
                    });
                }

                var semestry = new List<GenericListModel>();
                foreach (var s in wszystkieSemestry)
                {
                    semestry.Add(new GenericListModel
                    {
                        Id = s.Id,
                        Nazwa = $"{s.Rok} {Helpers.nazwaTypSemestru(s.Typ)}"
                    });
                }

                var kursoPrzedmiot = new List<GenericListModel>();
                foreach (var k in kursy)
                {
                    var przedmiot = przedmiotyOdKursow
                        .Where(p => p.Id == k.IdPrzedmiot)
                        .FirstOrDefault();

                    var forma = wszystkieFormyZajec
                        .Where(fz => fz.Id == k.IdFormaZajec)
                        .FirstOrDefault();

                    kursoPrzedmiot.Add(new GenericListModel
                    {
                        Id = k.Id,
                        Nazwa = $"[{k.Kod}] {przedmiot.nazwa}, {forma.nazwa}"
                    });
                }
                kursoPrzedmiot = kursoPrzedmiot.OrderBy(kp => kp.Nazwa).ToList();

                var formyZajec = new List<GenericListModel>();
                foreach (var fz in wszystkieFormyZajec)
                {
                    formyZajec.Add(new GenericListModel
                    {
                        Id = fz.Id,
                        Nazwa = fz.nazwa
                    });
                }

                var kursyPelne = new List<KursPelnyListModel>();
                foreach (var k in kursy)
                {
                    kursyPelne.Add(new KursPelnyListModel
                    {
                        Id = k.Id,
                        FormaZajec = formyZajec
                            .Where(fz => fz.Id == k.IdFormaZajec)
                            .Select(fz => fz.Nazwa)
                            .FirstOrDefault(),
                        LiczbaGodzin = k.LiczbaGodzinZZU
                    });
                }

                //zapełnianie modelu - tabela pracowników
                bool pusteTez = search.JednostkiOrganizacyjne.Contains(-1);
                foreach (var p in pracownicyTabela)
                {
                    if (search.JednostkiOrganizacyjne.Count == 0
                        || (p.IdJednostkaOrganizacyjna.HasValue
                            && search.JednostkiOrganizacyjne.Contains(p.IdJednostkaOrganizacyjna.Value))
                        || (pusteTez && !p.IdJednostkaOrganizacyjna.HasValue))
                    {
                        StringBuilder sb = new StringBuilder();

                        ZIRPService.ZainteresowaniaAkademickie[] zainteresowania
                            = serwisZirp.getInterestsByEmployee(p.Id, true);//już posortowane

                        if (zainteresowania.Length > 0)
                        {
                            sb.Append(zainteresowania[0].Nazwa);
                            for (int i = 1; i < zainteresowania.Length; i++)
                            {
                                sb.Append(", ");
                                sb.Append(zainteresowania[1].Nazwa);
                            }
                        }

                        ZIRPService.Stanowisko stanowisko = wszystkieStanowiska.Where(s => s.Id == p.IdStanowisko).FirstOrDefault();

                        viewModel.Pracownicy.Add(new PracownikModel
                        {
                            Id = p.Id,
                            JednostkaOrganizacyjna = wszystkieJO.Where(jo => jo.Id == p.IdJednostkaOrganizacyjna).Select(jo => jo.Skrot).FirstOrDefault(),
                            NazwiskoImie = $"{p.Nazwisko}, {p.Imie}",
                            TytulNaukowy = p.TytulyNaukowe,
                            Stanowisko = stanowisko.Nazwa,
                            Pensum = stanowisko.Pensum - p.ObnizeniePensum,
                            Zainteresowania = sb.ToString()
                        });
                    }
                }

                //zapełnianie modelu - tabela powierzeń
                foreach (var pow in powierzeniaTabela)
                {
                    //pracownicyOdPowierzen
                    //przedmiotyOdPowierzen
                    //kursy

                    ZIRPService.Kurs_Powierzenie_PracownikDydaktyczny kppd = serwisZirp.getLinkByCommittal(pow.Id, true);

                    ZIRPService.Kurs kurs = kursy.Where(k => k.Id == kppd.IdKurs).FirstOrDefault();

                    if (kurs == null)
                    {
                        throw new ArgumentNullException($"Mamy do czynienia z powierzeniem-widmo: bez kursu, bez serc, szkieletów to encje.<br/>(id powierzenia: {pow.Id})");
                    }

                    ZIRPService.Przedmiot przedmiot = przedmiotyOdKursow
                        .Where(p => p.Id == kurs.IdPrzedmiot)
                        .FirstOrDefault();

                    if (przedmiot == null)
                    {
                        throw new ArgumentNullException($"Mamy do czynienia z kursem bezprzedmiotowym.<br/>(id powierzenia: {pow.Id})");
                    }

                    ZIRPService.PracownikDydaktyczny pracownik = pracownicyOdPowierzen
                        .Where(p => p.Id == kppd.IdPracownikDydaktyczny)
                        .FirstOrDefault();

                    if (pracownik == null)
                    {
                        throw new ArgumentNullException($"Mamy do czynienia z powierzeniem bezpańskim: ktoś miał być powierzony, a nie jest.<br/>(id powierzenia: {pow.Id})");

NowaEdukacjaClient/Views/Powierzenia/Moje.cshtml
@using NowaEdukacjaClient.Models;
@model MojeViewModel

@{
    ViewBag.Title = "Moje powierzenia";
}

@using (Html.BeginForm("Moje", "Powierzenia", FormMethod.Get, new { id = "formPodszyj" }))
{
    
}

@using (Html.BeginForm("Zmien", "Powierzenia", FormMethod.Post, new { id = "formZmien" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="PodszyjSie" value="@Model.IdPracownik" />
    <input id="hiddenAkcja" type="hidden" name="Akcja" />
}

<div class="jumbotron">
    <p>
        Podszyj się pod pracownika
        <select name="PodszyjSie" form="formPodszyj">
            @foreach (GenericListModel p in ViewBag.pracownicy)
            {
            <option value="@p.Id" selected="@(p.Id == Model.IdPracownik)">@p.Nazwa</option>
            }
        </select>
        <button type="submit" form="formPodszyj">Podszyj się</button>
    </p>
</div>

<h2>Zaakceptowane</h2>

<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-1">
            <p>Całkowite pensum: @Model.CalkowitePensum</p>
        </div>
        <div class="col-md-5 col-md-offset-1">
            @if (Model.CalkowitePensum < Model.WykorzystanePensum)
            {
            <p class="alert-danger">Wykorzystane: @Model.WykorzystanePensum</p>
            }
            else
            {
            <p>Wykorzystane: @Model.WykorzystanePensum</p>
            }
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th style="width: 4em;">Lp.</th>
            <th>Jedn. org.</th>
            <th>Kurs</th>
            <th>Forma zajęć</th>
            <th style="width: 4em;">Godziny ZZU</th>
            <th>Liczba grup</th>
            <th>Komentarz</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Zaakceptowane.Count == 0)
        {
        <tr>
            <td>#</td>
            <td colspan="6"><i>brak zaakceptowanych powierzeń</i></td>
        </tr>
        }
        else
        {
            int lp = 1;
            foreach (PowierzenieModel p in Model.Zaakceptowane)
            {
        <tr>
            <td>@lp</td>
            <td>@p.JednOrg</td>
            <td>@p.Kurs</td>
            <td>@p.FormaZajec</td>
            <td>@p.LiczbaGodzin</td>
            <td>@p.LiczbaGrupZaakceptowana</td>
            <td>@p.Komentarz</td>
        </tr>
                lp++;
            }
        }
    </tbody>
</table>

<h2>Propozycje</h2>

<table class="table">
    <thead>
        <tr>
            <th style="width: 1em;"><input type="checkbox" onclick="toggleAll(this)" /></th>
            <th style="width: 4em;">Lp.</th>
            <th>Jedn. org.</th>
            <th>Kurs</th>
            <th>Forma zajęć</th>
            <th style="width: 4em;">Godziny ZZU</th>
            <th>Liczba grup</th>
            <th>Komentarz</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Propozycje.Count == 0)
        {
        <tr>
            <td></td>
            <td>#</td>
            <td colspan="6"><i>brak nowych propozycji</i></td>
        </tr>
        }
        else
        {
            int lp = 1;
            foreach (PowierzenieModel p in Model.Propozycje)
            {
        <tr>
            <td><input class="fnZmien" type="checkbox" name="Zmien[@(lp-1)].Accepted" form="formZmien" value="True" /></td>
            <td>
                @lp
                <input type="hidden" name="Zmien[@(lp-1)].Id" form="formZmien" value="@p.Id" />
            </td>
            <td>@p.JednOrg</td>
            <td>@p.Kurs</td>
            <td>@p.FormaZajec</td>
            <td>@p.LiczbaGodzin</td>
            <td>
                <input type="number" name="Zmien[@(lp-1)].LiczbaGrupZaakceptowana" form="formZmien" min="0" step="1" style="width: 3em; text-align: left;" value="@(p.LiczbaGrupZaakceptowana > 0 ? p.LiczbaGrupZaakceptowana : p.LiczbaGrupPowierzona)" />/@p.LiczbaGrupPowierzona
                <input type="hidden" name="Zmien[@(lp-1)].LiczbaGrupPowierzona" form="formZmien" value="@p.LiczbaGrupPowierzona" />
            </td>
            <td>
                <textarea name="Zmien[@(lp-1)].Komentarz" form="formZmien">@p.Komentarz</textarea>
            </td>
        </tr>
                lp++;
            }
        }
    </tbody>
</table>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn btn-success" onclick="propozycjeTak()">Zaakceptuj wybrane</button>
            <button type="button" class="btn btn-warning" onclick="propozycjeMoze()">Wyślij wybrane propozycje zmian</button>
            <button type="button" class="btn btn-danger" onclick="propozycjeNie()">Odrzuć wybrane</button>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function toggleAll(element)
        {
            if ($(element).prop("checked")) {
                $(".fnZmien").prop("checked", true);
            } else {
                $(".fnZmien").prop("checked", false);
            }
        }
    </script>
    <script>
        function propozycjeRoot(numerAkcji) {
            if ($(".fnZmien:checked").length == 0) {
                alert("Nie wybrano żadnych powierzeń!");
            }
            else {
                $("#hiddenAkcja").val(numerAkcji);
                $("#formZmien").submit();
            }
        }

        function propozycjeTak() {
            propozycjeRoot(1);
        }

        function propozycjeMoze() {
            propozycjeRoot(0);
        }

        function propozycjeNie() {
            propozycjeRoot(-1);
        }
    </script>
}

NowaEdukacjaClient/Views/Powierzenia/Przydzielaj.cshtml
@using NowaEdukacjaClient.Models;
@model PrzydzielajViewModel

@{
    ViewBag.Title = "Zarządzanie powierzeniami";
}

@using (Html.BeginForm("Przydzielaj", "Powierzenia", FormMethod.Get, new { id = "formSzukaj" }))
{

}

@using (Html.BeginForm("Przydziel", "Powierzenia", FormMethod.Post, new { id = "formPrzydziel" }))
{
    @Html.AntiForgeryToken()
    for (int i = 0; i < Model.JednostkiOrganizacyjne.Count; i++)
    {
        <input type="hidden" name="Szukaj.JednostkiOrganizacyjne[@i]" value="@Model.JednostkiOrganizacyjne[i]" />
    }
    <input type="hidden" name="Szukaj.Nazwisko" value="@Model.Nazwisko" />
    <input type="hidden" name="Szukaj.Imie" value="@Model.Imie" />
    <input type="hidden" name="Szukaj.Zainteresowanie" value="@Model.Zainteresowanie" />
    <input type="hidden" name="Szukaj.Tytul" value="@Model.Tytul" />
}

<h2>Pracownicy</h2>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <label style="width: 100%; text-align: right;">Jednostka organizacyjna</label>
        </div>
        <div class="col-md-8">
            <div id="jednostkiOrganizacyjne">
                <select name="JednostkiOrganizacyjne" form="formSzukaj" multiple="multiple">
                    <option value="-1" selected="@(Model.JednostkiOrganizacyjne.Contains(-1))">(bez przydziału)</option>
                    @foreach (JednostkaOrganizacyjnaListModel jo in ViewBag.jednostkiOrg)
                    {
                    <option value="@jo.Id" selected="@(Model.JednostkiOrganizacyjne.Contains(jo.Id))">@jo.Nazwa</option>
                    }
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label style="width: 100%; text-align: right;">Wyszukiwarka</label>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-4">
                    <input type="text" name="Nazwisko" form="formSzukaj" class="form-control" placeholder="nazwisko" value="@Model.Nazwisko" />
                </div>
                <div class="col-md-2">
                    <input type="text" name="Imie" form="formSzukaj" class="form-control" placeholder="imię" value="@Model.Imie" />
                </div>
                <div class="col-md-4">
                    <input type="text" name="Zainteresowanie" form="formSzukaj" class="form-control" placeholder="zainteresowania" value="@Model.Zainteresowanie" />
                </div>
                <div class="col-md-2">
                    <input type="text" name="Tytul" form="formSzukaj" class="form-control" placeholder="tytuł" value="@Model.Tytul" />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <button type="submit" form="formSzukaj" class="btn btn-primary">Szukaj</button>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Lp.</th>
            <th>Jedn.org.</th>
            <th>Nazwisko, imię</th>
            <th>Tytuł</th>
            <th>Stanowisko</th>
            <th>Pensum</th>
            <th>Zainteresowania</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Pracownicy.Count == 0)
        {
        <tr>
            <td colspan="8" style="text-align: center;">(brak wyników)</td>
        </tr>
        }
        else
        {
            int lp = 1;
            foreach (PracownikModel p in Model.Pracownicy)
            {
        <tr>
            <td>
                <input type="radio" name="Dodaj.IdPracownik" form="formPrzydziel" value="@p.Id" onclick="kopiujNazwisko(this)" />
            </td>
            <td>@lp</td>
            <td>@p.JednostkaOrganizacyjna</td>
            <td class="fnNazwisko">@p.NazwiskoImie</td>
            <td>@p.TytulNaukowy</td>
            <td>@p.Stanowisko</td>
            <td>@p.Pensum</td>
            <td>@p.Zainteresowania</td>
        </tr>
                lp++;
            }
        }
    </tbody>
</table>

<h2>Powierzenia</h2>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <label style="width: 100%; text-align: right;">Cykl kształcenia</label>
        </div>
        <div class="col-md-6">
            <select name="CyklKsztalcenia" form="formSzukaj" class="form-control">
                <option value="-1"></option>
                @foreach (GenericListModel ck in ViewBag.cykleKsztalcenia)
                {
                <option value="@ck.Id" selected="@(Model.CyklKsztalcenia == ck.Id)">@ck.Nazwa</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label style="width: 100%; text-align: right;">Plan studiów</label>
        </div>
        <div class="col-md-6">
            <select name="PlanStudiow" form="formSzukaj" class="form-control">
                <option value="-1"></option>
                @foreach (GenericListModel ps in ViewBag.planyStudiow)
                {
                <option value="@ps.Id" selected="@(Model.PlanStudiow == ps.Id)">@ps.Nazwa</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label style="width: 100%; text-align: right;">Semestr</label>
        </div>
        <div class="col-md-6">
            <select name="Semestr" form="formSzukaj" class="form-control">
                <option value="-1"></option>
                @foreach (GenericListModel s in ViewBag.semestry)
                {
                <option value="@s.Id" selected="@(Model.Semestr == s.Id)">@s.Nazwa</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <button type="submit" form="formSzukaj" class="btn btn-primary">Szukaj</button>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Lp.</th>
            <th style="width: 18em !important;">Kurs</th>
            <th style="width: 7em !important;">Forma zajęć</th>
            <th style="width: 7em !important;">L. godzin</th>
            <th style="width: 5em !important;">L. grup</th>
            <th>Pracownicy</th>
            <th style="width: 5em !important;">Akcept.?</th>
            <th>Komentarz</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Powierzenia.Count == 0)
        {
        <tr>
            <td colspan="8" style="text-align: center;">(brak wyników)</td>
        </tr>
        }
        else
        {
            int lp = 1;
            foreach (PowierzenieModel p in Model.Powierzenia)
            {
        <tr>
            <td>@lp</td>
            <td>@p.Kurs</td>
            <td>@p.FormaZajec</td>
            <td>@p.LiczbaGodzin</td>
            <td>
                @if (!p.CzyPowierzono)
                {
                @:@p.LiczbaGrupZaakceptowana / @p.LiczbaGrupPowierzona
                }
                else
                {
                    if (p.LiczbaGrupZaakceptowana == 0)
                    {
                @:<span class="alert-danger">@p.LiczbaGrupZaakceptowana / @p.LiczbaGrupPowierzona</span>
                    }
                    else if (p.LiczbaGrupZaakceptowana < p.LiczbaGrupPowierzona)
                    {
                @:<span class="alert-warning">@p.LiczbaGrupZaakceptowana / @p.LiczbaGrupPowierzona</span>
                    }
                    else
                    {
                @:<span class="alert-success">@p.LiczbaGrupZaakceptowana / @p.LiczbaGrupPowierzona</span>
                    }
                }
            </td>
            <td>@p.Pracownicy</td>
            <td>@(p.CzyPowierzono ? "tak" : "nie")</td>
            <td>@p.Komentarz</td>
        </tr>
                lp++;
            }
        }
        @if (ViewBag.kursy.Count > 0)
        {
        <tr id="nowePowierzenieWlaczacz" style="cursor: pointer;" onclick="pokazDodawanie()">
            <td>#</td>
            <td colspan="7"><i>kliknij, aby dodać nowe powierzenie</i></td>
        </tr>
        <tr id="nowePowierzenie" style="display: none;">
            <td>#</td>
            <td>
                <select id="kursId" name="Dodaj.IdKurs" form="formPrzydziel" class="form-control" onchange="ustawWartosci()">
                    <option value="-1"></option>
                    @foreach (GenericListModel k in ViewBag.kursy)
                    {
                        <option value="@k.Id">@k.Nazwa</option>
                    }
                </select>
            </td>
            <td>
                <span id="formaZajec"></span>
            </td>
            <td>
                <span id="liczbaGodzin"></span>
            </td>
            <td>
                <input type="number" name="Dodaj.LiczbaGrup" form="formPrzydziel" min="0" step="1" class="form-control" />
            </td>
            <td>
                <span id="pracownikNazwa" style="background-color: aliceblue;"></span>
                <br />
                <span style="font-size: smaller;">(wybierz z tabeli na górze)</span>
            </td>
            <td>
                (nie)
            </td>
            <td>(brak)</td>
        </tr>
        }
        else
        {
        <tr>
            <td>#</td>
            <td colspan="7"><i>nie ma żadnych kursów do przydzielenia na dany cykl, plan i/lub semestr</i></td>
        </tr>
        }
    </tbody>
</table>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <button type="submit" form="formPrzydziel" class="btn btn-success">Zapisz powierzenie</button>
            <button type="button" class="btn btn-info" disabled="disabled">Generuj raport do głosowania na radzie wydziału {wyłączone}</button>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $("#jednostkiOrganizacyjne").find(".ms-container").css("width", "100%");
    </script>
    <script>
        function pokazDodawanie() {
            $("#nowePowierzenieWlaczacz").css("display", "none");
            $("#nowePowierzenie").css("display", "table-row");
        };
    </script>
    <script>
        function kopiujNazwisko(element) {
            $("#pracownikNazwa").text(
                $(element).parent().parent().find(".fnNazwisko").text()
            );
        }
    </script>
    <script>
        var kursy = {
            @foreach (KursPelnyListModel k in ViewBag.kursyPelne)
            {
            @:@k.Id: { forma: "@Html.Raw(k.FormaZajec)", godziny: @k.LiczbaGodzin },
            }
        };

        function ustawWartosci() {
            var kursId = $("#kursId").val();
            $("#formaZajec").text(kursy[kursId].forma);
            $("#liczbaGodzin").text(kursy[kursId].godziny);
        }
    </script>
}