NowaEdukacjaClient/Controllers/SaleController.cs
using NowaEdukacjaClient.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NowaEdukacjaClient.Controllers
{
    public class SaleController : BaseNowaEdukacjaController
    {
        PlanowanieSalService.PlanowanieSalService serwisSale = new PlanowanieSalService.PlanowanieSalService();

        // GET: Szukaj
        public ActionResult Szukaj(SaleSearchModel search)
        {
            //wskazanie wejściowego modelu
            SaleSearchModel searchModel;

            SaleSearchModel tempSearchModel = (SaleSearchModel)TempData["search"];
            if (tempSearchModel != null)
            {
                searchModel = tempSearchModel;
            }
            else
            {
                searchModel = search;
            }

            {
                Debug.WriteLine($"searchModel.NumerSali {searchModel.NumerSali}");
                Debug.WriteLine($"searchModel.Budynek {searchModel.Budynek}");
                Debug.WriteLine($"searchModel.TypSali {searchModel.TypSali}");
                Debug.WriteLine($"searchModel.Wyposazenie {searchModel.Wyposazenie}");
                Debug.WriteLine($"searchModel.LimitMiejscMin {searchModel.LimitMiejscMin}");
                Debug.WriteLine($"searchModel.LimitMiejscMax {searchModel.LimitMiejscMax}");
            }//HACK usuń!

            //utworzenie pustego ViewModela
            SaleViewModel viewModel = new SaleViewModel();

            try
            {
                //odczyt z serwisów, wstępna filtracja
                List<PlanowanieSalService.Sala> przefiltrowaneSale;

                PlanowanieSalService.Budynek[] wszystkieBudynki = serwisSale.getAllBuildings();
                PlanowanieSalService.WyposazenieSali[] wszystkieWyposazenie = serwisSale.getAllEquipment();
                PlanowanieSalService.TypSali[] wszystkieTypy = serwisSale.getAllClassroomTypes();
                PlanowanieSalService.Sala[] wszystkieSale = serwisSale.getAllClassrooms();

                IEnumerable<PlanowanieSalService.Sala> filtrowaneSale = wszystkieSale.AsEnumerable();//TODO jeśli zdążymy: filtrowanie powinno być po stronie serwisu

                if (!string.IsNullOrWhiteSpace(searchModel.NumerSali))
                {
                    string num = searchModel?.NumerSali;
                    filtrowaneSale = filtrowaneSale.Where(s => s.Numer == num);
                }
                if (searchModel.Budynek != null)
                {
                    string bud = searchModel?.Budynek;
                    int? idBud = wszystkieBudynki.Where(b => b.Nazwa == bud).FirstOrDefault()?.Id;
                    if (idBud != null)
                    {
                        filtrowaneSale = filtrowaneSale.Where(s => s.IdBudynek == idBud);
                    }
                    else
                    {
                        filtrowaneSale = filtrowaneSale.Take(0);
                    }
                }
                if (searchModel.TypSali != null)
                {
                    int typ = searchModel.TypSali.Value;
                    filtrowaneSale = filtrowaneSale.Where(s => (int)(s.Typ) == typ);
                }
                if (searchModel.LimitMiejscMin != null)
                {
                    int limMin = searchModel.LimitMiejscMin.Value;
                    filtrowaneSale = filtrowaneSale.Where(s => s.LiczbaMiejsc >= limMin);
                }
                if (searchModel.LimitMiejscMax != null)
                {
                    int limMax = searchModel.LimitMiejscMax.Value;
                    filtrowaneSale = filtrowaneSale.Where(s => s.LiczbaMiejsc <= limMax);
                }

                Dictionary<int, PlanowanieSalService.WyposazenieSali[]> wyposazenieWSalach = new Dictionary<int, PlanowanieSalService.WyposazenieSali[]>();
                foreach (var sala in filtrowaneSale)
                {
                    PlanowanieSalService.WyposazenieSali[] wyp = serwisSale.getEquipmentByClassroom(sala.Id, true);//TODO isSpecified jest niepotrzebny?
                    wyposazenieWSalach.Add(sala.Id, wyp);
                }

                if (searchModel.Wyposazenie.Count > 0)
                {
                    przefiltrowaneSale = new List<PlanowanieSalService.Sala>();

                    foreach (var sala in filtrowaneSale)
                    {
                        PlanowanieSalService.WyposazenieSali[] wyp = wyposazenieWSalach[sala.Id];
                        if (searchModel.Wyposazenie.Intersect(wyp.Select(w => w.Id)).Count()
                            == searchModel.Wyposazenie.Count)
                        {
                            przefiltrowaneSale.Add(sala);
                        }
                    }
                }
                else
                {
                    przefiltrowaneSale = filtrowaneSale.ToList();
                }

                //zapełnienie ViewModela
                viewModel.NumerSali = searchModel.NumerSali;
                viewModel.Budynek = searchModel.Budynek;
                viewModel.TypSali = searchModel.TypSali;
                if (searchModel.Wyposazenie != null)
                {
                    viewModel.Wyposazenie = searchModel.Wyposazenie;
                }
                viewModel.LimitMiejscMin = searchModel.LimitMiejscMin;
                viewModel.LimitMiejscMax = searchModel.LimitMiejscMax;

                foreach (var sala in przefiltrowaneSale)
                {
                    int idBudynek = sala.IdBudynek;
                    StringBuilder sb = new StringBuilder();
                    PlanowanieSalService.WyposazenieSali[] wypo = wyposazenieWSalach[sala.Id];

                    if (wypo.Length > 0)
                    {
                        sb.Append(wypo[0].Nazwa);
                        for (int i = 1; i < wypo.Length; i++)
                        {
                            sb.Append(", ");
                            sb.Append(wypo[i].Nazwa);
                        }
                    }

                    viewModel.Sale.Add(new SalaModel
                    {
                        Id = sala.Id,
                        NumerSali = sala.Numer,
                        Budynek = wszystkieBudynki.Where(b => b.Id == idBudynek).FirstOrDefault()?.Nazwa,
                        TypSali = Helpers.nazwaTypSali(sala.Typ),
                        LiczbaMiejsc = sala.LiczbaMiejsc,
                        Wyposazenie = sb.ToString()
                    });
                }

                List<TypSaliListModel> typySal = new List<TypSaliListModel>();
                foreach (var ts in wszystkieTypy)
                {
                    typySal.Add(new TypSaliListModel { Id = (int)ts, Nazwa = Helpers.nazwaTypSali(ts) });
                }

                List<WyposazenieListModel> typyWyposazenia = new List<WyposazenieListModel>();
                foreach (var w in wszystkieWyposazenie)
                {
                    typyWyposazenia.Add(new WyposazenieListModel { Id = w.Id, Typ = w.Nazwa });
                }

                ViewBag.typySal = typySal;
                ViewBag.typyWyposazenia = typyWyposazenia;
            }
            catch (Exception e)
            {
                RespondError($"Wystąpił nieoczekiwany błąd.<br/>{e.Message}<br/>{e.StackTrace}");
                
                //ViewBagi zawierające list/arraye/cokolwiek co można dać do foreach() nie mogą być nullem
                ViewBag.typySal = new List<TypSaliListModel>();
                ViewBag.typyWyposazenia = new List<WyposazenieListModel>();
            }

            return View(viewModel);
        }

        // POST Dodaj
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dodaj(SalaAddModel Dodaj, SaleSearchModel Szukaj)
        {
            {
                Debug.WriteLine($" # Dodaj.NumerSali: {Dodaj.NumerSali}");
                Debug.WriteLine($" # Dodaj.Budynek: {Dodaj.Budynek}");
                Debug.WriteLine($" # Dodaj.TypSali: {Dodaj.TypSali}");
                Debug.WriteLine($" # Dodaj.Wyposazenie: {Dodaj.Wyposazenie}");
                Debug.WriteLine($" # Dodaj.LiczbaMiejsc: {Dodaj.LiczbaMiejsc}");
            }//HACK usuń

            try
            {
                bool sukcesSQL;

                if (Dodaj.TypSali == -1)
                {
                    RespondError("Typ sali musi być wybrany!");

                    TempData["search"] = Szukaj;

                    return RedirectToAction("Szukaj");
                }

                int idBudynku;

                PlanowanieSalService.Budynek budynek = serwisSale.getAllBuildings()
                    .Where(b => b.Nazwa == Dodaj.Budynek)
                    .FirstOrDefault();

                if (budynek == null)
                {
                    serwisSale.addBuilding(new PlanowanieSalService.Budynek
                    {
                        Nazwa = Dodaj.Budynek
                    }, out idBudynku, out sukcesSQL);

                    if (!sukcesSQL)
                    {
                        RespondError("Nie udało się dodać nowego budynku!<br />Nie dodano sali.");

                        TempData["search"] = Szukaj;

                        return RedirectToAction("Szukaj");
                    }
                }
                else
                {
                    idBudynku = budynek.Id;
                }

                Debug.WriteLine($"Budynek: {Dodaj.Budynek}; Id budynku: {idBudynku}");

                int resultId;

                serwisSale.addClassroom(new PlanowanieSalService.Sala
                {
                    Numer = Dodaj.NumerSali,
                    IdBudynek = idBudynku,
                    IdBudynekSpecified = true,
                    Typ = (PlanowanieSalService.TypSali)Dodaj.TypSali,
                    TypSpecified = true,

NowaEdukacjaClient/Controllers/UIMocksController.cs
using NowaEdukacjaClient.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NowaEdukacjaClient.Controllers
{
    public class UIMocksController : Controller
    {
        // GET: UIMocks
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

NowaEdukacjaClient/Views/UIMocks/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Poniżej lista linków do wstępnej implementacji interfejsów z parametrami:</h2>

<ul>
    <li>@Html.ActionLink("Sale", "Sale", new { liczbaSal = 15 })</li>
    <li></li>
    <li></li>
    <li></li>
</ul>

NowaEdukacjaClient/Views/UIMocks/Sale.cshtml
@using NowaEdukacjaClient.Models;
@model SaleViewModel

@{
    ViewBag.Title = "Sale";
}

<h2>Sale</h2>

@{ 
    System.Diagnostics.Debug.WriteLine($"Liczba sal: {ViewBag.liczbaSal}");
}

@using (Html.BeginForm("Sale", "UIMocks", FormMethod.Get, new { id = "formSzukaj" }))
{

}

@using (Html.BeginForm("Usun", "UIMocks", FormMethod.Post, new { id = "formUsun" }))
{
    @Html.AntiForgeryToken();
    <input type="hidden" name="id" />
    <input type="hidden" name="Szukaj.NumerSali" value="@Model.NumerSali" />
    <input type="hidden" name="Szukaj.Budynek" value="@Model.Budynek" />
    <input type="hidden" name="Szukaj.TypSali" value="@Model.TypSali" />
    for (int i = 0; i < Model.Wyposazenie.Count; i++)
    {
        <input type="hidden" name="Szukaj.Wyposazenie[@i]" value="@Model.Wyposazenie[i]" />
    }
    <input type="hidden" name="Szukaj.LimitMiejscMin" value="@Model.LimitMiejscMin" />
    <input type="hidden" name="Szukaj.LimitMiejscMax" value="@Model.LimitMiejscMax" />
}

@using (Html.BeginForm("Dodaj", "UIMocks", FormMethod.Post, new { id = "formDodaj" }))
{
    @Html.AntiForgeryToken();
    <input type="hidden" name="Szukaj.NumerSali" value="@Model.NumerSali" />
    <input type="hidden" name="Szukaj.Budynek" value="@Model.Budynek" />
    <input type="hidden" name="Szukaj.TypSali" value="@Model.TypSali" />
    for (int i = 0; i < Model.Wyposazenie.Count; i++)
    {
        <input type="hidden" name="Szukaj.Wyposazenie[@i]" value="@Model.Wyposazenie[i]" />
    }
    <input type="hidden" name="Szukaj.LimitMiejscMin" value="@Model.LimitMiejscMin" />
    <input type="hidden" name="Szukaj.LimitMiejscMax" value="@Model.LimitMiejscMax" />
}


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label style="width: 100%; text-align: right;">Numer sali</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <input type="text" name="NumerSali" form="formSzukaj" style="width: 100%;" class="form-control" placeholder="201, 1.30, 107a, ..." value="@Model.NumerSali" />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label style="width: 100%; text-align: right;">Budynek</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <input type="text" name="Budynek" form="formSzukaj" style="width: 100%;" class="form-control" placeholder="C-3, D-1, A-1, ..." value="@Model.Budynek" />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label style="width: 100%; text-align: right;">Typ sali</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <select name="TypSali" form="formSzukaj" style="width: 100%;" class="form-control">
                <option value=""></option>
                @foreach (TypSaliModel t in ViewBag.typySal)
                {
                <option value="@t.Id" selected="@(Model.TypSali == t.Id)">@t.Nazwa</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label style="width: 100%; text-align: right;">Wyposażenie dodatkowe</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <select name="Wyposazenie" form="formSzukaj" size="4" style="width: 100%;" class="form-control" multiple="multiple">
                @foreach (WyposazenieModel w in ViewBag.typyWyposazenia)
                {
                <option value="@w.Id" selected="@(Model.Wyposazenie.Contains(w.Id))">@w.Typ</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3">
            <label style="width: 100%; text-align: right;">Limity miejsc</label>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1">
            <label style="width: 100%; text-align: right;">min.</label>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1">
            <input type="number" name="LimitMiejscMin" form="formSzukaj" style="width: 100%;" class="form-control" step="1" min="0" value="@Model.LimitMiejscMin" />
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1 col-md-offset-1">
            <label style="width: 100%; text-align: right;">max.</label>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1">
            <input type="number" name="LimitMiejscMax" form="formSzukaj" style="width: 100%;" class="form-control" step="1" min="0" value="@Model.LimitMiejscMax" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4" style="text-align: center;">
            <button type="submit" form="formSzukaj" class="btn btn-primary">Szukaj</button>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Lp.</th>
            <th>Numer sali</th>
            <th>Budynek</th>
            <th>Typ sali</th>
            <th>Liczba miejsc</th>
            <th>Wyposażenie</th>
            <th>Akcja</th>
        </tr>
    </thead>
    <tbody id="saleBody">
        @{ int lp = 1; }
        @foreach (var item in Model.Sale)
        {
        <tr>
            <td>
                @lp
            </td>
            <td style="white-space: nowrap;">
                @Html.DisplayFor(modelItem => item.NumerSali)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Budynek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypSali)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LiczbaMiejsc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wyposazenie)
            </td>
            <td>
                @Html.HiddenFor(modelItem => item.NumerSali, new { @class = "fnUsunNumerSali" })
                @Html.HiddenFor(modelItem => item.Budynek, new { @class = "fnUsunBudynek" })
                @Html.HiddenFor(modelItem => item.Id, new { @class = "fnUsunId" })
                <button type="button" onclick="usun(this)" class="btn btn-danger">Usuń {TODO}</button>
            </td>
        </tr>
            lp++;
        }
        <tr id="nowaSalaWlaczacz" style="cursor: pointer;" onclick="pokazDodawanie()">
            <td>#</td>
            <td colspan="6"><i>kliknij, aby dodać nową</i></td>
        </tr>
        <tr id="nowaSala" style="display: none;">
            <td>#</td>
            <td>
                <input type="text" name="Dodaj.NumerSali" form="formDodaj" class="form-control" placeholder="201" value="@Model.NumerSali" />
            </td>
            <td>
                <input type="text" name="Dodaj.Budynek" form="formDodaj" class="form-control" placeholder="C-13" value="@Model.Budynek" />
            </td>
            <td>
                <select name="Dodaj.TypSali" form="formDodaj" class="form-control">
                    <option value="-1"></option>
                    @foreach (TypSaliModel t in ViewBag.typySal)
                    {
                    <option value="@t.Id" selected="@(Model.TypSali == t.Id)">@t.Nazwa</option>
                    }
                </select>
            </td>
            <td>
                <input type="number" name="Dodaj.LiczbaMiejsc" form="formDodaj" value="0" step="1" min="0" class="form-control" />
            </td>
            <td>
                <select name="Dodaj.Wyposazenie" form="formDodaj" multiple="multiple">
                    @foreach (WyposazenieModel w in ViewBag.typyWyposazenia)
                    {
                    <option value="@w.Id" selected="@(Model.Wyposazenie.Contains(w.Id))">@w.Typ</option>
                    }
                </select>
            </td>
            <td>
                <button type="button" onclick="dodaj(this)" class="btn btn-success">Dodaj {TODO}</button>
            </td>
        </tr>
    </tbody>
</table>

@section scripts {
    <script>
        function pokazDodawanie() {
            $("#nowaSalaWlaczacz").css("display", "none");
            $("#nowaSala").css("display", "table-row");
        };

        function usun(element) {
            var komorka = $(element).parent();
            var potwierdz = confirm("Czy na pewno chcesz usunąć salę "
                + komorka.find(".fnUsunNumerSali").val()
                + " w budynku "
                + komorka.find(".fnUsunBudynek").val()
                + "?");

            if (potwierdz) {
                $("#formUsun").find("input[name='id']").val(komorka.find(".fnUsunId").val());
                $("#formUsun").submit();
            }
        }

        function dodaj(element) {
            $("#formDodaj").submit();
        }
    </script>
}